### ISSUE TITLE
Gebruikersonderzoek

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#11]

**Comment by norayesnir** [comment]
# Gebruikers Onderzoek,

Om te weten wie onze gebruikers zijn moeten we eerst weten wat we gaan doen. Het idee is op dit moment bijna helemaal duidelijk. Wij als team Mokum hebben de kunstenaar Tim Walker gekozen voor ons project. Hij is een bekende fotografeur die Chaotische Klassieke en oudbollige foto's maakt en daarom willen wij met ons project een fotoshoot doen in zijn style. Daarom gaan wij een BOX maken met een echte Tim Walker sfeer. In de BOX zijn ook interactieve onderdelen zoals bewegende schilderijen en QR-codes op zijn plek om meer informatie te geven aan het onderwerp waar het bij staat.

### Maar wie wilt dit gaan bezoeken?
Het project is voor The Upside Down; dat best veel jongeren aan trekt door de grote invloed op social media zoals TikTok & Instagram. Omdat wij een fotoshoot gaan doen willen wij op de zelfde groep gaan richten. Dus voor alle mensen die actief zijn op social media en een geweldige foto willen maken van de geniale kunstenaar 'Tim Walker'. Wij zoeken cultuursnuivers en mensen zoekend naar een nieuwe ervaring om langs te komen!

### Het onderzoek
Wij hebben een form gestuurd naar ~30 mogelijke kandidaten die geïnteresseerd zouden kunnen zijn om deze ervaring mee te maken. Aan de kandidaten hebben wij 13 vragen gesteld waar wij conclusies uit gaan trekken. 


#### De eerste vraag was natuurlijk hoe oud de kandidaten waren
![Image](https://user-images.githubusercontent.com/92859617/205499886-f667a617-81bc-41d0-b07e-2861444549a3.png)

Hieraan kunnen we zien hoe de 30 mensen verschillen in leeftijd. Bijna de helft van de kandidaten is onder de 16.


#### Daarna hadden wij gevraagd of ze de Influencer Anna Nooshin kennen (de oprichter van The Upside Down)
![Image](https://user-images.githubusercontent.com/92859617/205500194-f138d6b6-b99e-4398-bd7a-4251eddafb0b.png)

Daar kennen de meeste mensen haar niet, maar een redelijk groot deel wel. Ook zien we dat de meeste oudere mensen haar wel kennen en de mensen onder 19 haar niet kennen

#### Ook hebben we gevraagd of de kandidaten Tim Walker kennen.
![Image](https://user-images.githubusercontent.com/92859617/205500306-23bc36f3-a40e-4009-aa49-ed435c866879.png)

Voor mij is het een verassing dat 14.3% van de kandidaten Tim Walker kent. Dat vind ik nog een best groot aantal. Wel zijn de kandidaten die hem kennen grotendeels boven de 22 jaar oud.

#### We moesten ook eventjes recht stellen hoevaak de kandidaten musea's bezoekt. 
![Image](https://user-images.githubusercontent.com/92859617/205500437-3674efc1-4056-41be-bb04-2e45dd41b248.png)

Hier hebben wij 14.3% die elke week een musea bezoekt! Dat vind ik persoonlijk extreem veel. Maar ook 28.6% die Nooit naar musea's gaat! De rest van de kandidaten verdelen zich over Bijna nooit en gemiddeld vaak.

#### Maar hoeveel mensen zijn nou geïnteresseerd in fotografie?
![Image](https://user-images.githubusercontent.com/92859617/205500950-ad2188f9-37fb-4a8f-a318-cfd824927787.png)

Bij deze vraag krijgen wij een beetje 2 polen van antwoorden. Precies 42.9% van de kandidaten zijn Heel erg geïnteresseerd in fotografie en ook 42.6% een beetje. 14.6% vind het helemaal niets. Ook concluderen wij hieruit dat vooral de jongeren juist _wel_ geïnteresseerd is in fotografie.

#### Ook hebben we de vraag gesteld of de kandidaten geïnteresseerd zijn in kunst.
![Image](https://user-images.githubusercontent.com/92859617/205501118-fff8bf8c-1f80-454b-9868-0432e8f9766b.png)

Daar komt uit dat _niemand_ helemaal niet geïnteresseerd is in kunst!

#### Maar zijn de kandidaten wel eens naar het Wondr Museum geweest?
![Image](https://user-images.githubusercontent.com/92859617/205501199-cc7e5897-4523-4417-8a35-012f8c109c8f.png)

Daar komt vooral een dikke nee uit, met 14.3% die daar wel is geweest.

#### Nu komen er wat vragen meer gericht op de jongeren. Met als eerste vraag hoevaak de kandidaten op hun telefoon zitten
![Image](https://user-images.githubusercontent.com/92859617/205501368-e06714cb-0a60-4f7d-871c-f20380b3c981.png)

#### Maken de kandidaten gebruik maken van social media?
![Image](https://user-images.githubusercontent.com/92859617/205501458-82494844-161c-473c-8819-0f3b3ba7509e.png)

Daarvan maakt 28.6% gebruik van TikTok, 71% van Instagram, 14.3% van Twitter, & 57.1% van Snapchat.

#### Ook wouden we graag weten of onze kandidaten Creatief zijn.
![Image](https://user-images.githubusercontent.com/92859617/205501559-88cd5a23-51da-4828-b87f-cb61ba36d485.png)

#### En als laatst de vraag of de kandidaten veel gebruik maken van het openbaar-vervoer.
![Image](https://user-images.githubusercontent.com/92859617/205501608-c4c22623-9d41-43a0-8b4e-5ac9314ebe1e.png)

**Comment by HommieNommie** [comment]
[gebruikersonderzoek kylie.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10158420/gebruikersonderzoek.kylie.pdf)
