### ISSUE TITLE
Persona

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#12]

**Comment by norayesnir** [comment]
### Persona
_Deze persona is gebaseerd op het gebruikers onderzoek_

___


Mijn naam is Olivia, ik ben 18 jaar oud en woon in Maarssen. Mijn Moeder komt uit Ecuador en mijn vader is Nederlands. Ik ben zelf gewoon in Nederland geboren. Ik houd van tekenen en creatief met mijn handen werken. En het liefst lig ik de hele dag in bed. 

Ik houd er van om creatief te zijn. En om geïnspireerd te worden. Toen ik klein was maakte ik vaak miniature kunstwerkjes te maken. Bijvoorbeeld mini boekjes voor in mijn zelfde maakte miniature huis. Ik doe daarom ook de studie Ruimtelijk Ontwerp, Kunst en Cultuur op het Nimeto. Daarvoor moet ik elke dag met de trein naar Utrecht.

![Image](https://user-images.githubusercontent.com/92859617/205503725-090416a0-9a29-4cf7-b52a-0972349c568c.png)

Mijn moeder neemt mij vaak mee naar musea's. Eerst was het geforceerd en moest ik altijd mee maar de laatste tijd vind ik het erg interessant om mee te gaan naar musea's die iets met ruimtelijk ontwerp te maken heeft zoals fotografie musea's .


![Image](https://user-images.githubusercontent.com/92859617/205503889-c87f25a5-c536-456d-9164-0f78bcd3d597.png)

**Comment by norayesnir** [comment]
Eind Persona @norayesnir 

[Persona.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10153587/Persona.pdf)

**Comment by HommieNommie** [comment]
[persona kylie.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10159050/persona.kylie.pdf)
