### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#14]

**Comment by norayesnir** [comment]
@AliCMA @DDammers-MA @yusufMAO , Wat is de status van deze issue?

**Comment by AliCMA** [comment]
Ik had dit al een tijdje geleden af, was vergeten het af te vinken.

**Comment by norayesnir** [comment]
@AliCMA  Kan je in een comment uploaden wat je hebt, dan kunnen we de issue sluiten

**Comment by AliCMA** [comment]
Ga ik doen

**Comment by norayesnir** [comment]
![Image](https://user-images.githubusercontent.com/92859617/205517363-82ffddd9-49a5-43af-80a7-2f45a1300296.png)

Dit moet issue 14 ziijn

**Comment by AliCMA** [comment]
[Projectplan Upside-down.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10152040/Projectplan.Upside-down.pdf)
