### ISSUE TITLE
Werktekening

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#42]

**Comment by MimiDew** [comment]
[WerkTekening Ruimte.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10149003/WerkTekening.Ruimte.pdf)

Dit is de werktekening pdf file

**Comment by norayesnir** [comment]
Moet er niets in de box komen? Als in een Tim Walker style dekoor als backdrop voor de fotoshoot?

**Comment by MimiDew** [comment]
de leraar zij dat ik alleen de box moest maken omdat dat in elkaar gezet word als een geheel de rest word geshowd in de visual

**Comment by norayesnir** [comment]
Dan hoor je mij niet meer, Goed gedaan! Dan is deze issue klaar. 👏

**Comment by MimiDew** [comment]
[WerkTekening Ruimte 002.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10208493/WerkTekening.Ruimte.002.pdf)


Dit is de nieuwe werktekening omdat er een paar maten waren aangewezen

**Comment by MimiDew** [comment]
[WerkTekening Ruimte 003.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10237643/WerkTekening.Ruimte.003.pdf)

Werktekening weer aangepast na beoordeling van kjell :)

**Comment by norayesnir** [comment]
Update



[WerkTekening Ruimte 004.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10487788/WerkTekening.Ruimte.004.pdf)
