### ISSUE TITLE
Concept Presentatie

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#53]
Gelieve alle afgeronden taken te uploading voor in de Concept Presentatie.
(Upload je iets van iemand anders, Zet dan erbij wie het heeft gemaakt!)

Ga je iets niet af krijgen hoor ik het ook graag!

# Presentatie Checklist

#### Oriënterend Onderzoek:
- [x] #3 @everyone

Oriënterend Onderzoek: Foto Opdracht #1 
> - [x] Fotobingo @everyone
> - [x] Smoelenboek @leahaha420 

##### ALL
- [x] #8 @norayesnir 
- [x] #9 @HommieNommie 
- [x] #10 @norayesnir @danidioot @HommieNommie 

---

#### Media Vormgeving | MV

Debriefing #5 
> - [x] @norayesnir | Interactive Debriefing
> - [x] @danidioot | ???
> - [x] @HommieNommie | ???

Persona #12 
> - [x] @norayesnir | Persona Olivia
> - [x] @danidioot | ???
> - [x] @HommieNommie | ???

Visueel Concept #13 
> - [x] @norayesnir | Webapp
> - [x] @danidioot | ???
> - [x] @HommieNommie | ???

Gebruikersprofiel #56 
> - [x] @norayesnir | Webapp
> - [x] @danidioot | ???
> - [x] @HommieNommie | ???

User Journey #7 
> - [x] @norayesnir | QR-scan
> - [x] @danidioot | ???
> - [x] @HommieNommie | ???

Gebruikersonderzoek #11 
> - [x] @norayesnir
> - [x] @danidioot 
> - [x] @HommieNommie 

- [x] #6 @danidioot @HommieNommie 
- [x] #52 @norayesnir

---

#### Software Development | SD

- [x] #26  @AliCMA 
- [x] #15  @DDammers-MA
- [x] #55 @yusufMAO 
- [x] #14  @AliCMA  

---

#### Ruimtelijk Vormgever | RV

- [x] #41 @leahaha420 
- [x] #40 @leahaha420 
- [x] #43  @leahaha420 
- [x] #42 @MimiDew

**Comment by norayesnir** [comment]
Oriënterend Onderzoek Foto Bingo: Smoelenboek => #1

**Comment by DDammers-MA** [comment]
Inverters mokum project software developer
weet niet of dit echt alles is

Camera / camera stand/ lensen 
Beamer 
Lichten / studio lampen 
Stuurlampen 
Lampstatief
Cabels voor voor camera
Stekker block
Reserveonderdelen
Knoppen 
Raspeaawberry pie

**Comment by DDammers-MA** [comment]
[input&output onderzoek BO.docx](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10152939/input.output.onderzoek.BO.docx)
