### ISSUE TITLE
Gebruikers Profiel

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#56]
Iedereen eigen gebruikersprofiel maken van zijn/haar product.

**Comment by norayesnir** [comment]
# Gebruikersprofiel Interactieve opdracht AR/VR
> Rinse Yaron Schaeffer

**Comment by HommieNommie** [comment]
[gebruikersprofiel kylie.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10158649/gebruikersprofiel.kylie.pdf)
