### ISSUE TITLE
Moodboard

### ISSUE THREAD

**Issue by norayesnir** [norayesnir/Radicale_Kunstspeeltuin#9]

**Comment by norayesnir** [comment]
@HommieNommie, Kan jij hier de Moodboard uploaden die jij op die gekke locatie had gemaakt?

**Comment by HommieNommie** [comment]
[Tim Walker Moodboard.pdf](https://github.com/norayesnir/Radicale_Kunstspeeltuin/files/10156528/Tim.Walker.Moodboard.pdf)

**Comment by norayesnir** [comment]
Toppie
